# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e0525ab53a7bf4e80206d1730655f1cdef0350b1c5b1a9389fda1fa60293699d9a67cd6194386686f695ad13d591e4fdc7169928fbda5dd7ed351d8fec0c0c2

test:
  secret_key_base: 7e7e6b082142f723064e4bb8ff4a13f7568b369136e22145010e4ef12ef094fa8a8a3c6c18e2120ddca301bcc11512b234d7033a257a7a7eea3899c6f4e48649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
